---
 
name: GCP Bucket Deployment
on: 
  workflow_dispatch:
    inputs:
      Operation_Needed:
        type: choice
        description: Select from menu 
        options:
          - Select Operation to be Performed
          - Create
          - Delete 
        required: true
      # GCP_Service:
      #   type: choice
      #   description: Choose GCP Service  
      #   options:
      #     - Select GCP service you want to deploy
      #     - Storage Bucket
      #     - Cloud function  
        # required: true
      Name:
        description: 'Name'
        required: true
      Region:
        description: 'Region'
        required: true

jobs:
  GCP_Create_Bucket:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.Operation_Needed == 'Create' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with: 
          python-version: 3.8

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'

      - name: Install pip package for gcloud
        run: pip install google-cloud-storage
        
      - name: Execute Python code
        run: |
          name_of_bucket=${{ github.event.inputs.Name }} region=${{ github.event.inputs.Region }} python Python_scripts/create_bucket.py

  GCP_Delete_Bucket:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.Operation_Needed == 'Delete' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with: 
          python-version: 3.8

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'

      - name: Install pip package for gcloud
        run: pip install google-cloud-storage
        
      - name: Execute Python code to Delete GCP Bucket
        run: |
          name_of_bucket=${{ github.event.inputs.Name }} python Python_scripts/delete_bucket.py

    
        