---
name: Pylint
on:
  workflow_run:
    workflows: ["validation"]
    types:
      - requested
      - completed
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step-1
        run: echo "Pylint"