name: yamllint
on:
 push:
  branches:
   - test
 pull_request:
  branches:
   - test
jobs:
  whitespaces:
    name: Find Trailing Whitespace
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: harupy/find-trailing-whitespace@master
  build:
    runs-on: ubuntu-latest
    needs: whitespaces
    steps:
      - uses: actions/checkout@master
      - name: Run action
        uses: jacobtomlinson/gha-lint-yaml@master
        with:
          path: .github/workflows/lint.yaml



